[project]
name = "pdf-to-md"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "requests>=2.25.0",
    "python-dotenv>=0.19.0"
]
